name: angular_dart_todo_benchmark
version: 0.0.1
dependencies:
  angular:
    path: ../angular-dart
  browser: any
  unittest: any
  benchmark_harness: any

transformers:
- angular
- $dart2js:
    minify: false
    checked: false
